# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envcmd < Formula
  desc "Command line tool for running per-environment commands."
  homepage "https://github.com/brooknullsh/envcmd"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brooknullsh/envcmd/releases/download/v0.3.1/envcmd_Darwin_x86_64.tar.gz"
      sha256 "7e5513874ea7b85fab7f27552b9d7e04bc4d5b15ce166decc387f61ac0c33a06"

      def install
        bin.install "envcmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brooknullsh/envcmd/releases/download/v0.3.1/envcmd_Darwin_arm64.tar.gz"
      sha256 "fd3424d986cdeefab39398fc2b750cfbe9d2d1203142da906fa6f69a62eae477"

      def install
        bin.install "envcmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/brooknullsh/envcmd/releases/download/v0.3.1/envcmd_Linux_x86_64.tar.gz"
      sha256 "0689b11b949d506f4c233ff248a8f26b0be62c803d502032a05eeab791e209a1"
      def install
        bin.install "envcmd"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/brooknullsh/envcmd/releases/download/v0.3.1/envcmd_Linux_arm64.tar.gz"
      sha256 "3fa8c98915296ce29b71ffc7287e2b10fde6841199adacc504f61bce11f3bb2a"
      def install
        bin.install "envcmd"
      end
    end
  end
end
