# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envcmd < Formula
  desc "Command line tool for running per-environment commands."
  homepage "https://github.com/brooknullsh/envcmd"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brooknullsh/envcmd/releases/download/v0.4.2/envcmd_Darwin_x86_64.tar.gz"
      sha256 "1c2b0858038181da8a83f3f43dbbebe43ca1be3e25dd07fc13d457436410cb63"

      def install
        bin.install "envcmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brooknullsh/envcmd/releases/download/v0.4.2/envcmd_Darwin_arm64.tar.gz"
      sha256 "eea4e1eb945c93ae7b8ad4cf054e2ace81a52736f83f9ca3f4d63f94ecc5fcf8"

      def install
        bin.install "envcmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/brooknullsh/envcmd/releases/download/v0.4.2/envcmd_Linux_x86_64.tar.gz"
      sha256 "46c86ccbc6fc0d57cad3a09eca15b63c9b3c6c9a247d9a3d0a5453ac03e0dcf8"
      def install
        bin.install "envcmd"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/brooknullsh/envcmd/releases/download/v0.4.2/envcmd_Linux_arm64.tar.gz"
      sha256 "edfb5c14daa9aed19d5babf927ed981a47681e71d6d89575e799c89086fea89a"
      def install
        bin.install "envcmd"
      end
    end
  end
end
